### ISSUE TITLE
Finish first pass of preprocessor

### ISSUE THREAD

**Issue by hawkins** [hawkins/druid#2]
- [x] Handle `#summon` in `apply`
  - Read file in `parameter` and write in-place into `fp`
- [ ] Write output to `stdout`
  - For use in feeding downstream, to lexical analyzer.
- [ ] Read files into memory instead of continuously reading/writing to disk

**Comment by hawkins** [comment]
How would `#define` be handled?

**Comment by assemblyDruid** [comment]
Going to close this to better focus the preprocessor (formerly first-pass-preprocessor) branch; starting new issue list.
